# Generated by Django 3.2.3 on 2021-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusInjetoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.TextField()),
            ],
        ),
    ]
